2017-05-29 16:58:50|ERROR|User.chklogin|PDOException: Unknown column 'user_id' in 'field list' in D:\WWW\1\test\PhalApi\NotORM\NotORM\Result.php:246
Stack trace:
#0 D:\WWW\1\test\PhalApi\NotORM\NotORM\Result.php(780): NotORM_Result->query('SELECT user_id,...', Array)
#1 D:\WWW\1\test\PhalApi\NotORM\NotORM\Result.php(826): NotORM_Result->execute()
#2 D:\WWW\1\test\PhalApi\PhalApi\Model\NotORM.php(38): NotORM_Result->fetch()
#3 D:\WWW\1\test\Bbs\Api\User.php(33): PhalApi_Model_NotORM->getInfo(Array, 'user_id, userna...')
#4 D:\WWW\1\test\PhalApi\PhalApi.php(55): Api_User->chklogin()
#5 D:\WWW\1\test\index.php(17): PhalApi->response()
#6 {main}
2017-05-29 16:58:54|ERROR|User.chklogin|PDOException: Unknown column 'user_id' in 'field list' in D:\WWW\1\test\PhalApi\NotORM\NotORM\Result.php:246
Stack trace:
#0 D:\WWW\1\test\PhalApi\NotORM\NotORM\Result.php(780): NotORM_Result->query('SELECT user_id,...', Array)
#1 D:\WWW\1\test\PhalApi\NotORM\NotORM\Result.php(826): NotORM_Result->execute()
#2 D:\WWW\1\test\PhalApi\PhalApi\Model\NotORM.php(38): NotORM_Result->fetch()
#3 D:\WWW\1\test\Bbs\Api\User.php(33): PhalApi_Model_NotORM->getInfo(Array, 'user_id, userna...')
#4 D:\WWW\1\test\PhalApi\PhalApi.php(55): Api_User->chklogin()
#5 D:\WWW\1\test\index.php(17): PhalApi->response()
#6 {main}
2017-05-29 16:59:03|ERROR|User.chklogin|PDOException: Unknown column 'user_auth' in 'field list' in D:\WWW\1\test\PhalApi\NotORM\NotORM\Result.php:246
Stack trace:
#0 D:\WWW\1\test\PhalApi\NotORM\NotORM\Result.php(780): NotORM_Result->query('SELECT id, user...', Array)
#1 D:\WWW\1\test\PhalApi\NotORM\NotORM\Result.php(826): NotORM_Result->execute()
#2 D:\WWW\1\test\PhalApi\PhalApi\Model\NotORM.php(38): NotORM_Result->fetch()
#3 D:\WWW\1\test\Bbs\Api\User.php(33): PhalApi_Model_NotORM->getInfo(Array, 'id, username, p...')
#4 D:\WWW\1\test\PhalApi\PhalApi.php(55): Api_User->chklogin()
#5 D:\WWW\1\test\index.php(17): PhalApi->response()
#6 {main}
